apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2022-09-15T17:48:35Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: fluentbit-gke
    kubernetes.io/cluster-service: "true"
  name: fluentbit-gke
  namespace: kube-system
  resourceVersion: "1209946"
  uid: 6e8ad1d7-1a5e-49ca-808a-e7451de453d7
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: fluentbit-gke
      k8s-app: fluentbit-gke
  template:
    metadata:
      annotations:
        EnableNodeJournal: "false"
        EnablePodSecurityPolicy: "false"
        SystemOnlyLogging: "false"
        components.gke.io/component-name: fluentbit
        components.gke.io/component-version: 1.7.4
        monitoring.gke.io/path: /api/v1/metrics/prometheus
      creationTimestamp: null
      labels:
        component: fluentbit-gke
        k8s-app: fluentbit-gke
        kubernetes.io/cluster-service: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-max-pods-per-node
                operator: DoesNotExist
              - key: cloud.google.com/gke-logging-variant
                operator: NotIn
                values:
                - MAX_THROUGHPUT
            - matchExpressions:
              - key: cloud.google.com/gke-max-pods-per-node
                operator: Lt
                values:
                - "111"
              - key: cloud.google.com/gke-logging-variant
                operator: NotIn
                values:
                - MAX_THROUGHPUT
      containers:
      - image: gke.gcr.io/fluent-bit:v1.8.7-gke.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 2020
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: fluentbit
        ports:
        - containerPort: 2020
          hostPort: 2020
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - DAC_OVERRIDE
            drop:
            - all
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/google-fluentbit/pos-files
          name: varrun
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/kubelet/pods
          name: varlibkubeletpods
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: config-volume
      - command:
        - /fluent-bit-gke-exporter
        - --kubernetes-separator=_
        - --stackdriver-resource-model=k8s
        - --enable-pod-label-discovery
        - --pod-label-dot-replacement=_
        - --split-stdout-stderr
        - --stackdriver-timeout=60s
        - --logtostderr
        image: gke.gcr.io/fluent-bit-gke-exporter:v0.17.1-gke.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 2021
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        name: fluentbit-gke
        ports:
        - containerPort: 2021
          hostPort: 2021
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentbit-gke
      serviceAccountName: fluentbit-gke
      terminationGracePeriodSeconds: 120
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: components.gke.io/gke-managed-components
        operator: Exists
      volumes:
      - hostPath:
          path: /var/run/google-fluentbit/pos-files
          type: ""
        name: varrun
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/kubelet/pods
          type: ""
        name: varlibkubeletpods
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - configMap:
          defaultMode: 420
          name: fluentbit-gke-config-v1.1.2
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 1
  updatedNumberScheduled: 2
